import requests
from bs4 import BeautifulSoup
import pandas as pd
from typing import List, Dict, Optional
import logging
import os
from pathlib import Path

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class ScriptCollector:
    def __init__(self, output_dir: str = "data/raw_scripts"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
    def collect_from_imsdb(self, movie_title: str) -> Optional[Dict]:
        """Collect script from IMSDb."""
        try:
            # Format title for URL
            formatted_title = movie_title.lower().replace(" ", "-")
            url = f"https://imsdb.com/scripts/{formatted_title}.html"
            
            response = requests.get(url)
            if response.status_code != 200:
                logger.warning(f"Failed to fetch script for {movie_title}")
                return None
                
            soup = BeautifulSoup(response.text, 'html.parser')
            script_text = soup.find('pre').text
            
            return {
                'title': movie_title,
                'source': 'IMSDb',
                'content': script_text
            }
        except Exception as e:
            logger.error(f"Error collecting from IMSDb: {str(e)}")
            return None
            
    def collect_from_kaggle(self, dataset_path: str) -> List[Dict]:
        """Collect scripts from Kaggle dataset."""
        try:
            df = pd.read_csv(dataset_path)
            scripts = []
            
            for _, row in df.iterrows():
                scripts.append({
                    'title': row['title'],
                    'source': 'Kaggle',
                    'content': row['script']
                })
                
            return scripts
        except Exception as e:
            logger.error(f"Error collecting from Kaggle: {str(e)}")
            return []
            
    def save_script(self, script_data: Dict) -> bool:
        """Save collected script to file."""
        try:
            filename = f"{script_data['title'].lower().replace(' ', '_')}.txt"
            filepath = self.output_dir / filename
            
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(f"Title: {script_data['title']}\n")
                f.write(f"Source: {script_data['source']}\n")
                f.write("\nScript Content:\n")
                f.write(script_data['content'])
                
            logger.info(f"Saved script for {script_data['title']}")
            return True
        except Exception as e:
            logger.error(f"Error saving script: {str(e)}")
            return False
            
    def collect_scripts(self, movie_titles: List[str], kaggle_dataset: Optional[str] = None) -> None:
        """Main method to collect scripts from multiple sources."""
        # Collect from IMSDb
        for title in movie_titles:
            script_data = self.collect_from_imsdb(title)
            if script_data:
                self.save_script(script_data)
                
        # Collect from Kaggle if dataset provided
        if kaggle_dataset:
            scripts = self.collect_from_kaggle(kaggle_dataset)
            for script in scripts:
                self.save_script(script)

if __name__ == "__main__":
    # Example usage
    collector = ScriptCollector()
    #CrimeMovies
    movies = ["10 Things I Hate About You",
    "12",
    "12 Monkeys",
    "12 Years a Slave",
    "12 and Holding",
    "127 Hours",
    "1492: Conquest of Paradise",
    "15 Minutes",
    "17 Again",
    "187",
    "2001: A Space Odyssey",
    "2012",
    "20th Century Women",
    "25th Hour",
    "28 Days Later",
    "30 Minutes or Less",
    "42",
    "44 Inch Chest",
    "48 Hrs.",
    "50-50",
    "500 Days of Summer",
    "8 Mile",
    "8MM",
    "9",
    "A Few Good Men",
    "A Good Person",
    "A Million Miles Away",
    "A Most Violent Year",
    "A Perfect World, A",
    "A Prayer Before Dawn",
    "A Quiet Place",
    "A Real Pain",
    "A Scanner Darkly",
    "A Serious Man",
    "A.I.",
    "Above the Law",
    "Absolute Power",
    "Abyss, The",
    "Ace Ventura: Pet Detective",
    "Ad Astra",
    "Adaptation",
    "Addams Family, The",
    "Adjustment Bureau, The",
    "Adventures of Buckaroo Banzai Across the Eighth Dimension, The",
    "Affliction",
    "After School Special",
    "After.Life",
    "Agnes of God",
    "Air",
    "Air Force One",
    "Airplane",
    "Airplane 2: The Sequel",
    "Aladdin Transcript",
    "Ali",
    "Alien",
    "Alien 3",
    "Alien Nation",
    "Alien vs. Predator",
    "Alien: Resurrection",
    "Aliens",
    "All About Eve",
    "All About Steve",
    "All of Us Strangers",
    "All the King's Men",
    "All the President's Men",
    "Almost Famous",
    "Alone in the Dark",
    "Amadeus",
    "Amelia",
    "American Beauty",
    "American Fiction",
    "American Gangster",
    "American Graffiti",
    "American History X",
    "American Hustle",
    "American Madness",
    "American Milkshake",
    "American Outlaws",
    "American Pie",
    "American President, The",
    "American Psycho",
    "American Shaolin: King of Kickboxers II",
    "American Sniper",
    "American Splendor",
    "American Werewolf in London",
    "American, The",
    "Amityville Asylum, The",
    "Amour",
    "An Education",
    "Analyze That",
    "Analyze This",
    "Anastasia",
    "Angel Eyes",
    "Angels & Demons",
    "Anna Karenina",
    "Annie Hall",
    "Anniversary Party, The",
    "Anonymous",
    "Anora Green",
    "Antitrust",
    "Antz",
    "Apartment, The",
    "Apocalypse Now",
    "Apollo 13",
    "April Fool's Day",
    "Apt Pupil",
    "Arbitrage",
    "Arcade",
    "Arctic Blue",
    "Argo",
    "Armageddon",
    "Army of Darkness",
    "Arsenic and Old Lace",
    "Arthur",
    "Artist, The",
    "As Good As It Gets",
    "Assassins",
    "Assignment, The",
    "Asteroid City",
    "At First Sight",
    "August: Osage County",
    "Austin Powers - International Man of Mystery",
    "Austin Powers - The Spy Who Shagged Me",
    "Authors Anonymous",
    "Autumn in New York",
    "Avatar",
    "Avengers, The",
    "Avengers: Endgame",
    "Avventura, L' (The Adventure)",
    "Awakenings",
    "Babel",
    "Bachelor Party",
    "Bachelor Party, The",
    "Back to the Future",
    "Back to the Future II & III",
    "Back-up Plan, The",
    "Backdraft",
    "Bad Boys",
    "Bad Country",
    "Bad Day at Black Rock",
    "Bad Dreams",
    "Bad Lieutenant",
    "Bad Santa",
    "Bad Teacher",
    "Badlands",
    "Bamboozled",
    "Barbie",
    "Barry Lyndon",
    "Barton Fink",
    "Basic",
    "Basic Instinct",
    "Basquiat",
    "Batman",
    "Batman 2",
    "Batman Begins",
    "Batman Forever",
    "Batman Returns",
    "Batman and Robin",
    "Battle of Algiers, The",
    "Battle of Shaker Heights, The",
    "Battle: Los Angeles",
    "Beach, The",
    "Bean",
    "Beasts of No Nation",
    "Beasts of the Southern Wild",
    "Beauty and the Beast",
    "Beavis and Butt-head Do America",
    "Beekeeper, The",
    "Beginners",
    "Being Human",
    "Being John Malkovich",
    "Being There",
    "Being the Ricardos",
    "Believer, The",
    "Belle",
    "Beloved",
    "Benny & Joon",
    "Best Exotic Marigold Hotel, The",
    "Big",
    "Big Blue, The",
    "Big Eyes",
    "Big Fish",
    "Big Lebowski, The",
    "Big Sick, The",
    "Big White, The",
    "Birdman",
    "Birds, The",
    "Birthday Girl",
    "BlacKkKlansman",
    "Black Dahlia, The",
    "Black Panther",
    "Black Rain",
    "Black Snake Moan",
    "Black Swan",
    "Blackberry",
    "Blade",
    "Blade II",
    "Blade Runner",
    "Blade: Trinity",
    "Blast from the Past, The",
    "Blind Side, The",
    "Bling Ring, The",
    "Blink Twice",
    "Blitz",
    "Blood Simple",
    "Blood and Wine",
    "Blow",
    "Blue Valentine",
    "Blue Velvet",
    "Blues Brothers, The",
    "Bodies, Rest & Motion",
    "Body Heat",
    "Body of Evidence",
    "Bodyguard",
    "Bones",
    "Bonfire of the Vanities",
    "Bonnie and Clyde",
    "Boogie Nights",
    "Book of Eli, The",
    "Bookworm",
    "Boondock Saints 2: All Saints Day",
    "Boondock Saints, The",
    "Bottle Rocket",
    "Bound",
    "Bounty Hunter, The",
    "Bourne Identity, The",
    "Bourne Supremacy, The",
    "Bourne Ultimatum, The",
    "Box, The",
    "Boxtrolls, The",
    "Boyhood",
    "Braveheart",
    "Brazil",
    "Break",
    "Breakdown",
    "Breakfast Club, The",
    "Breaking Away",
    "Brick",
    "Bridesmaids",
    "Bringing Out the Dead",
    "Broadcast News",
    "Broken Arrow",
    "Broken Embraces",
    "Brothers Bloom, The",
    "Bruce Almighty",
    "Brutalist, The",
    "Buffy the Vampire Slayer",
    "Bull Durham",
    "Buried",
    "Burlesque",
    "Burn After Reading",
    "Burning Annie",
    "Butterfly Effect, The",
    "Cable Guy",
    "Candle to Water",
    "Capote",
    "Carrie",
    "Cars 2",
    "Casablanca",
    "Case 39",
    "Casino",
    "Cassandro",
    "Cast Away",
    "Catch Me If You Can",
    "Catwoman",
    "Cecil B. Demented",
    "Cedar Rapids",
    "Celeste & Jesse Forever",
    "Cell, The",
    "Cellular",
    "Change-Up, The",
    "Changeling",
    "Chaos",
    "Charade",
    "Charlie's Angels",
    "Chasing Amy",
    "Chasing Sleep",
    "Cherry Falls",
    "Chinatown",
    "Christ Complex",
    "Chronicle",
    "Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "Cider House Rules, The",
    "Cincinnati Kid, The",
    "Cinema Paradiso",
    "Cirque du Freak: The Vampire's Assistant",
    "Citizen Kane",
    "City of Joy",
    "Clash of the Titans",
    "Clerks",
    "Cliffhanger",
    "Clockwork Orange, A",
    "Clueless",
    "Cobb",
    "Coco",
    "Code of Silence",
    "Cold Mountain",
    "Collateral",
    "Collateral Damage",
    "Colombiana",
    "Color Purple, The",
    "Color of Night",
    "Commando",
    "Conan the Barbarian",
    "Confessions of a Dangerous Mind",
    "Confidence",
    "Constantine",
    "Contact",
    "Cooler, The",
    "Copycat",
    "Coraline",
    "Coriolanus",
    "Corpse Bride",
    "Courage Under Fire",
    "Cowboys & Aliens",
    "Cradle 2 the Grave",
    "Crank",
    "Crash",
    "Crazy, Stupid, Love",
    "Crazylove",
    "Creation",
    "Crime Spree",
    "Croods, The",
    "Crouching Tiger, Hidden Dragon",
    "Croupier",
    "Crow Salvation, The",
    "Crow, The",
    "Crow: City of Angels, The",
    "Cruel Intentions",
    "Crying Game",
    "Cube",
    "Curious Case of Benjamin Button, The",
    "Custody","Cider House Rules, The",
    "Cincinnati Kid, The",
    "Cinema Paradiso",
    "Cirque du Freak: The Vampire's Assistant",
    "Citizen Kane",
    "City of Joy",
    "Clash of the Titans",
    "Clerks",
    "Cliffhanger",
    "Clockwork Orange, A",
    "Clueless",
    "Cobb",
    "Coco",
    "Code of Silence",
    "Cold Mountain",
    "Collateral",
    "Collateral Damage",
    "Colombiana",
    "Color Purple, The",
    "Color of Night",
    "Commando",
    "Conan the Barbarian",
    "Confessions of a Dangerous Mind",
    "Confidence",
    "Constantine",
    "Contact",
    "Cooler, The",
    "Copycat",
    "Coraline",
    "Coriolanus",
    "Corpse Bride",
    "Courage Under Fire",
    "Cowboys & Aliens",
    "Cradle 2 the Grave",
    "Crank",
    "Crash",
    "Crazy, Stupid, Love",
    "Crazylove",
    "Creation",
    "Crime Spree",
    "Croods, The",
    "Crouching Tiger, Hidden Dragon",
    "Croupier",
    "Crow Salvation, The",
    "Crow, The",
    "Crow: City of Angels, The",
    "Cruel Intentions",
    "Crying",
    "Cube",
    "Curious Case of Benjamin Button, The",
    "Custody",
    "Dallas Buyers Club",
    "Damned United, The",
    "Dances with Wolves",
    "Danish Girl, The",
    "Dark City",
    "Dark Knight Rises, The",
    "Dark Knight, The",
    "Dark Star",
    "Darkman",
    "Date Night",
    "Dave Barry's Complete Guide to Guys",
    "Dawn of the Dead",
    "Day of the Dead",
    "Day the Clown Cried, The",
    "Day the Earth Stood Still, The",
    "Days of Heaven",
    "Dead Poets Society",
    "Deadpool",
    "Deadpool & Wolverine",
    "Dear White People",
    "Death at a Funeral",
    "Death to Smoochy",
    "Debt, The",
    "Deception",
    "Deep Cover",
    "Deep Rising",
    "Deer Hunter, The",
    "Defiance",
    "Departed, The",
    "Descendants, The",
    "Despicable Me 2",
    "Detroit Rock City",
    "Devil Wears Prada, The",
    "Devil in a Blue Dress",
    "Devil's Advocate",
    "Die Hard",
    "Die Hard 2",
    "Diner",
    "Distinguished Gentleman, The",
    "Disturbia",
    "Django Unchained",
    "Do The Right Thing",
    "Dog Day Afternoon",
    "Dogma",
    "Donnie Brasco",
    "Donnie Darko",
    "Doors, The",
    "Double Indemnity",
    "Drag Me to Hell",
    "Dragonslayer",
    "Dream Scenario",
    "Drive",
    "Drive Angry",
    "Drop Dead Gorgeous",
    "Dry White Season, A",
    "Duck Soup",
    "Dumb and Dumber",
    "Dune",
    "Dune Part One",
    "E.T.",
    "Eagle Eye",
    "Eastern Promises",
    "Easy A",
    "Ed TV",
    "Ed Wood",
    "Edward Scissorhands",
    "Eight Legged Freaks",
    "El Mariachi",
    "Election",
    "Elemental",
    "Elephant Man, The",
    "Elizabeth: The Golden Age",
    "Elvis",
    "Enemy of the State",
    "English Patient, The",
    "Enough",
    "Entrapment",
    "Equilibrium",
    "Erik the Viking",
    "Erin Brockovich",
    "Escape From L.A.",
    "Escape From New York",
    "Eternal Sunshine of the Spotless Mind",
    "Even Cowgirls Get the Blues",
    "Event Horizon",
    "Evil Dead",
    "Evil Dead II: Dead by Dawn",
    "Ex Machina",
    "Excalibur",
    "Executive Decision",
    "Extract",
    "Eyes Wide Shut",
    "Fabulous Baker Boys, The",
    "Face Off",
    "Fair",
    "FairyTale: A True Story",
    "Family Man, The",
    "Fantastic Beasts and Where to Find Them",
    "Fantastic Beasts: The Crimes of Grindelwald",
    "Fantastic Beasts: The Secrets of Dumbledore",
    "Fantastic Four",
    "Fantastic Mr Fox",
    "Fargo",
    "Fast Times at Ridgemont High",
    "Fatal Instinct",
    "Fault in Our Stars, The",
    "Fear and Loathing in Las Vegas",
    "Feast",
    "Ferrari",
    "Ferris Bueller's Day Off",
    "Field of Dreams",
    "Fifth Element, The",
    "Fight Club",
    "Fighter, The",
    "Final Destination",
    "Final Destination 2",
    "Finding Nemo",
    "First Cow",
    "Five Easy Pieces",
    "Flash Gordon",
    "Fletch",
    "Flight",
    "Flintstones, The",
    "Flora and Son",
    "Foe",
    "Forrest Gump",
    "Four Feathers",
    "Four Rooms",
    "Foxcatcher",
    "Fracture",
    "Frances",
    "Frankenstein",
    "Frankenweenie",
    "Freaked",
    "Fred Claus",
    "Freddy vs. Jason",
    "French Connection, The",
    "Frequency",
    "Freud's Last Session",
    "Friday the 13th",
    "Friday the 13th Part VIII: Jason Takes Manhattan",
    "Fright Night",
    "From Dusk Till Dawn",
    "From Here to Eternity",
    "Frozen",
    "Frozen (Disney)",
    "Frozen River",
    "Fruitvale Station",
    "Fugitive, The",
    "Full Metal Jacket",
    "Funny People",
    "Fury",
    "G.I. Jane",
    "G.I. Joe: The Rise of Cobra",
    "Game 6",
    "Game, The",
    "Gamer",
    "Gandhi",
    "Gang Related",
    "Gangs of New York",
    "Garden State",
    "Gattaca",
    "Get Carter",
    "Get Low",
    "Get Out",
    "Get Shorty",
    "Get on Up",
    "Getaway, The",
    "Ghost",
    "Ghost Rider",
    "Ghost Ship",
    "Ghost World",
    "Ghost and the Darkness, The",
    "Ghostbusters",
    "Ghostbusters 2",
    "Ginger Snaps",
    "Girl with the Dragon Tattoo, The",
    "Gladiator",
    "Glengarry Glen Gross",
    "Go",
    "Godfather",
    "Godfather Part II",
    "Godfather Part III, The",
    "Gods and Monsters",
    "Godzilla",
    "Gone Baby Gone",
    "Gone in 60 Seconds",
    "Good Girl, The",
    "Good Will Hunting",
    "Goodfellas",
    "Gothika",
    "Grabbers",
    "Graduate, The",
    "Gran Torino",
    "Grand Hotel",
    "Grand Theft Parsons",
    "Grapes of Wrath, The",
    "Gravity",
    "Great Gatsby, The",
    "Green Mile, The",
    "Gremlins",
    "Gremlins 2",
    "Grifters, The",
    "Grosse Point Blank",
    "Groundhog Day",
    "Grudge, The",
    "Guardians of the Galaxy Vol 2",
    "Hackers",
    "Hall Pass",
    "Halloween",
    "Halloween: The Curse of Michael Myers",
    "Hancock",
    "Hangover, The",
    "Hanna",
    "Hannah and Her Sisters",
    "Hannibal",
    "Happy Birthday, Wanda June",
    "Happy Feet",
    "Hard Rain",
    "Hard to Kill",
    "Harold and Kumar Go to White Castle",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Deathly Hallows Part 1",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Half-Blood Prince",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Sorcerer's Stone",
    "Haunting, The",
    "He's Just Not That Into You",
    "Heat",
    "Heathers",
    "Heavenly Creatures",
    "Heavy Metal",
    "Hebrew Hammer, The",
    "Heist",
    "Hellbound: Hellraiser II",
    "Hellboy",
    "Hellboy 2: The Golden Army",
    "Hellraiser",
    "Hellraiser 3: Hell on Earth",
    "Hellraiser: Deader",
    "Hellraiser: Hellseeker",
    "Help, The",
    "Henry Fool",
    "Henry's Crime",
    "Her",
    "Here Comes Peter Cottontail",
    "Hesher",
    "High Fidelity",
    "Highlander",
    "Highlander: Endgame",
    "Hills Have Eyes, The",
    "His Girl Friday",
    "Hitchcock",
    "Hitchhiker's Guide to the Galaxy, The",
    "Holdovers, The",
    "Hollow Man",
    "Honeydripper",
    "Horrible Bosses",
    "Horse Whisperer, The",
    "Hospital, The",
    "Hostage",
    "Hot Tub Time Machine",
    "Hotel Rwanda",
    "House of 1000 Corpses",
    "How to Lose Friends & Alienate People",
    "How to Train Your Dragon",
    "How to Train Your Dragon 2",
    "Hudson Hawk",
    "Hudsucker Proxy, The",
    "Human Nature",
    "Hunt for Red October, The",
    "Hurt Locker, The",
    "I Am Number Four",
    "I Love You Phillip Morris",
    "I Spit on Your Grave",
    "I Still Know What You Did Last Summer",
    "I am Sam",
    "I'll Do Anything",
    "I, Robot",
    "Ice Storm, The",
    "Ides of March, The",
    "Imaginarium of Doctor Parnassus, The",
    "In the Bedroom",
    "In the Loop",
    "Inception",
    "Incredibles, The",
    "Independence Day",
    "Indiana Jones IV",
    "Indiana Jones and the Last Crusade",
    "Indiana Jones and the Raiders of the Lost Ark",
    "Indiana Jones and the Temple of Doom",
    "Informant, The",
    "Inglourious Basterds",
    "Initiation",
    "Innerspace",
    "Insider, The",
    "Insidious",
    "Insomnia",
    "Interstellar",
    "Interview with the Vampire",
    "Into the Wild",
    "Into the Woods",
    "Intolerable Cruelty",
    "Inventing the Abbotts",
    "Invention of Lying, The",
    "Invictus",
    "Iron Claw, The",
    "Iron Lady, The",
    "Island, The",
    "It",
    "It Happened One Night",
    "It's Complicated",
    "It's a Wonderful Life",
    "Italian Job, The",
    "JFK",
    "Jacket, The",
    "Jackie Brown",
    "Jacob's Ladder",
    "Jade",
    "Jane Eyre",
    "Jason X",
    "Jaws",
    "Jaws 2",
    "Jay and Silent Bob Strike Back",
    "Jennifer Eight",
    "Jennifer's Body",
    "Jerry Maguire",
    "Jeux Interdits",
    "Jimmy and Judy",
    "John Q",
    "John Wick",
    "John Wick: Chapter 4",
    "Jojo Rabbit",
    "Joker",
    "Judge Dredd",
    "Juno",
    "Jurassic Park",
    "Jurassic Park III",
    "Jurassic Park: The Lost World",
    "Kafka",
    "Kalifornia",
    "Kate & Leopold",
    "Kids",
    "Kids Are All Right, The",
    "Kill Bill Volume 1 & 2",
    "Kill Your Darlings",
    "Killer, The",
    "Killers of the Flower Moon",
    "Killing Zoe",
    "King Kong",
    "King of Comedy, The",
    "King's Speech, The",
    "Kingdom, The",
    "Kiss of the Spider Woman",
    "Klute",
    "Knocked Up",
    "Kramer vs Kramer",
    "Kundun",
    "Kung Fu Panda",
    "L.A. Confidential",
    "LEGO Movie, The",
    "La La Land",
    "Labor of Love",
    "Labyrinth",
    "Ladykillers, The",
    "Lake Placid",
    "Land of the Dead",
    "Larry Crowne",
    "Last Boy Scout, The",
    "Last Chance Harvey",
    "Last Flight, The",
    "Last Samurai, The",
    "Last Station, The",
    "Last Tango in",
    "Last of the Mohicans, The",
    "Law Abiding Citizen",
    "Le Diable par la Queue",
    "Leaving Las Vegas",
    "Legally Blonde",
    "Legend",
    "Legion",
    "Leprechaun 2",
    "Les Miserables",
    "Les Tontons Flingueurs",
    "Lethal Weapon",
    "Lethal Weapon 4",
    "Leviathan",
    "Liar Liar",
    "Life",
    "Life As A House",
    "Life of David Gale, The",
    "Life of Pi",
    "Light Sleeper",
    "Limey, The",
    "Limitless",
    "Lincoln",
    "Lincoln Lawyer, The",
    "Lion King, The",
    "Little Athens",
    "Little Men",
    "Little Mermaid, The",
    "Little Nicky",
    "Living in Oblivion",
    "Lock, Stock and Two Smoking Barrels",
    "Logan",
    "Logan's Run",
    "Lone Star",
    "Long Kiss Goodnight, The",
    "Looper",
    "Lord of Illusions",
    "Lord of War",
    "Lord of the Rings: Fellowship of the Ring, The",
    "Lord of the Rings: Return of the King",
    "Lord of the Rings: The Two Towers",
    "Losers, The",
    "Lost Highway",
    "Lost Horizon",
    "Lost in Space",
    "Lost in Translation",
    "Love and Basketball",
    "Machete",
    "Machine Gun Preacher",
    "Mad Max 2: The Road Warrior",
    "Made",
    "Maestro",
    "Magnolia",
    "Majestic, The (The Bijou)",
    "Major League",
    "Malcolm X",
    "Malibu's Most Wanted",
    "Malignant",
    "Man On Fire",
    "Man Trouble",
    "Man Who Knew Too Much, The",
    "Man Who Wasn't There, The",
    "Man in the Iron Mask",
    "Man on the Moon",
    "Manchurian Candidate, The",
    "Manhattan Murder Mystery",
    "Manhunter",
    "Margaret",
    "Margin Call",
    "Margot at the Wedding",
    "Mariachi, El",
    "Marley & Me",
    "Martha Marcy May Marlene",
    "Martian, The",
    "Marty",
    "Mary Poppins",
    "Mask, The",
    "Master and Commander",
    "Master, The",
    "Matchstick Men",
    "Matrix Reloaded, The",
    "Matrix, The",
    "Max Payne",
    "May December",
    "Mean Streets",
    "Mechanic, The",
    "Meet Joe Black",
    "Meet John Doe",
    "Megamind",
    "Memento",
    "Memory",
    "Men Who Stare at Goats, The",
    "Men in Black",
    "Men in Black 3",
    "Menu, The",
    "Metro",
    "Miami Vice",
    "Midnight Cowboy",
    "Midnight Express",
    "Midnight in",
    "Mighty Joe Young",
    "Mighty Morphin Power Rangers: The Movie",
    "Milk",
    "Miller's Crossing",
    "Miller's Girl",
    "Mimic",
    "Mini's First Time",
    "Minority Report",
    "Miracle Worker, The",
    "Mirrors",
    "Misery",
    "Mission Impossible",
    "Mission Impossible II",
    "Mission to Mars",
    "Moneyball",
    "Monkeybone",
    "Monster's Ball",
    "Monte Carlo",
    "Moon",
    "Moonrise Kingdom",
    "Moonstruck",
    "Mr Blandings Builds His Dream House",
    "Mr Brooks",
    "Mr Deeds Goes to Town",
    "Mr. Holland's Opus",
    "Mrs. Brown",
    "Mud",
    "Mulan",
    "Mulholland Drive",
    "Mumford",
    "Mummy, The",
    "Music of the Heart",
    "Mute Witness",
    "My Best Friend's Wedding",
    "My Girl",
    "My Mother Dreams the Satan's Disciples in New York",
    "My Week with Marilyn",
    "Mystery Men",
    "Napoleon",
    "Napoleon Dynamite",
    "Nashville",
    "Natural Born Killers",
    "Never Been Kissed",
    "Neverending Story, The",
    "New York Minute",
    "Newsies",
    "Next",
    "Next Friday",
    "Next Three Days, The",
    "Ni vu ni connu",
    "Nick of Time",
    "Nickel Boys",
    "Night Time",
    "Nightbreed",
    "Nightmare Before Christmas, The",
    "Nightmare on Elm Street, A",
    "Nightmare on Elm Street: The Final Chapter",
    "Nine",
    "Nines, The",
    "Ninja Assassin",
    "Ninotchka",
    "Ninth Gate, The",
    "No Country for Old Men",
    "No Hard Feelings",
    "No One Will Save You",
    "No Strings Attached",
    "Notting Hill",
    "Nurse Betty",
    "O Brother Where Art Thou?",
    "Oblivion",
    "Observe and Report",
    "Obsessed",
    "Ocean's Eleven",
    "Ocean's Twelve",
    "Office Space",
    "Officer and a Gentleman, An",
    "Omega Man",
    "One Flew Over the Cuckoo's Nest",
    "Only God Forgives",
    "Onward",
    "Oppenheimer",
    "Ordinary People",
    "Orgy of the Dead",
    "Origin",
    "Orphan",
    "Other Boleyn Girl, The",
    "Out of Sight",
    "Outbreak",
    "Pacifier, The",
    "Pandorum",
    "Panic Room",
    "Papadopoulos & Sons",
    "ParaNorman",
    "Pariah",
    "Passengers",
    "Passion of Joan of Arc, The",
    "Patriot, The",
    "Paul",
    "Pearl Harbor",
    "Peeping Tom",
    "Peggy Sue Got Married",
    "Perfect Creature",
    "Perfect World, A",
    "Perks of Being a Wallflower, The",
    "Persian Version, The",
    "Pet Sematary",
    "Pet Sematary II",
    "Petulia",
    "Philadelphia",
    "Phone Booth",
    "Pi",
    "Pianist, The",
    "Piano, The",
    "Pineapple Express",
    "Pirates of the Caribbean",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Pitch Black",
    "Planet of the Apes, The",
    "Platinum Blonde",
    "Platoon",
    "Pleasantville",
    "Point Break",
    "Pokemon: Mewtwo Returns",
    "Poor Things",
    "Postman, The",
    "Power of One, The",
    "Precious",
    "Predator",
    "Prestige, The",
    "Pretty Woman",
    "Pride and Prejudice",
    "Priest",
    "Princess Bride, The",
    "Priscilla",
    "Private Life of Sherlock Holmes, The",
    "Producer, The",
    "Program, The",
    "Prom Night",
    "Prometheus",
    "Prophecy, The",
    "Proposal, The",
    "Psycho",
    "Public Enemies",
    "Pulp Fiction",
    "Punch-Drunk Love",
    "Purple Rain",
    "Puss in Boots: The Last Wish",
    "Quantum Project",
    "Queen of the Damned",
    "Queen, The",
    "Quiz Lady",
    "RKO 281",
    "Rachel Getting Married",
    "Raging Bull",
    "Raising Arizona",
    "Rambling Rose",
    "Rambo: First Blood II: The Mission",
    "Reader, The",
    "Real Genius",
    "Rear Window",
    "Rebel Without A Cause",
    "Red Planet",
    "Red Riding Hood",
    "Reindeer Games",
    "Relic, The",
    "Remember Me",
    "Replacements, The",
    "Repo Man",
    "Rescuers Down Under, The",
    "Reservoir Dogs",
    "Resident Evil",
    "Return of the Apes",
    "Revenant, The",
    "Revolutionary Road",
    "Ricky Stanicky",
    "Ringu",
    "Rise of the Guardians",
    "Rise of the Planet of the Apes",
    "Road, The",
    "Robin Hood: Prince of Thieves",
    "Robocop",
    "Rock, The",
    "RocknRolla",
    "Rocky",
    "Rocky Horror Picture Show, The",
    "Romeo & Juliet",
    "Ronin",
    "Room",
    "Roommate, The",
    "Rosetta",
    "Roughshod",
    "Ruins, The",
    "Runaway Bride",
    "Rush",
    "Rush Hour",
    "Rush Hour 2",
    "Rushmore",
    "Rust and Bone",
    "Rustin",
    "S. Darko",
    "Saint, The",
    "Salton Sea, The",
    "Sandlot Kids, The",
    "Saturday Night",
    "Save the Last Dance",
    "Saving Mr. Banks",
    "Saving Private Ryan",
    "Saw",
    "Saw IV",
    "Scarface",
    "Scary Movie 2",
    "Schindler's List",
    "Scott Pilgrim vs the World",
    "Scream",
    "Scream 2",
    "Scream 3",
    "Scream 4",
    "Se7en",
    "Searchers, The",
    "Secret Life of Walter Mitty, The",
    "Semi-Pro",
    "Sense and Sensibility",
    "Serenity",
    "Serial Mom",
    "Sessions, The",
    "Seventh Seal, The",
    "Sex and the City",
    "Sex, Lies and Videotape",
    "Sexual Life",
    "Shadow of the Vampire",
    "Shakespeare in Love",
    "Shallow Grave",
    "Shame",
    "Shampoo",
    "Shawshank Redemption, The",
    "She's Out of My League",
    "Sherlock Holmes",
    "Shifty",
    "Shining, The",
    "Shipping News, The",
    "Shivers",
    "Shrek",
    "Shrek the",
    "Sicario",
    "Sideways",
    "Siege, The",
    "Signs",
    "Silence of the Lambs",
    "Silent Grace",
    "Silver Bullet",
    "Silver Linings Playbook",
    "Simone",
    "Sing Sing",
    "Single White Female",
    "Sister Act",
    "Six Degrees of Separation",
    "Sixth Sense, The",
    "Sleepless in Seattle",
    "Sleepy Hollow",
    "Sling Blade",
    "Slither",
    "Slumdog Millionaire",
    "Smashed",
    "Smokin' Aces",
    "Snatch",
    "Sneakers",
    "Snow Falling On Cedars",
    "Snow White and the Huntsman",
    "So I Married an Axe Murderer",
    "Social Network, The",
    "Solaris",
    "Soldier",
    "Someone To Watch Over Me",
    "Something's Gotta Give",
    "Source Code",
    "South Park: Bigger, Longer & Uncut",
    "Space Milkshake",
    "Spanglish",
    "Spare Me",
    "Spartan",
    "Speed",
    "Speed Racer",
    "Sphere",
    "Spider-Man",
    "Spider-Man: Across the Spider-Verse",
    "St. Elmo's Fire",
    "Star Trek",
    "Star Trek II: The Wrath of Khan",
    "Star Trek: First Contact",
    "Star Trek: Generations",
    "Star Trek: Nemesis",
    "Star Trek: The Motion Picture",
    "Star Wars: A New Hope",
    "Star Wars: Attack of the Clones",
    "Star Wars: Return of the Jedi",
    "Star Wars: Revenge of the Sith",
    "Star Wars: The Empire Strikes Back",
    "Star Wars: The Force Awakens",
    "Star Wars: The Phantom Menace",
    "Starman",
    "Starship Troopers",
    "State and Main",
    "Station West",
    "Stepmom",
    "Sting, The",
    "Stir of Echoes",
    "Storytelling",
    "Straight Outta Compton",
    "Strange Days",
    "Strangers on a Train",
    "Stuntman, The",
    "Substance, The",
    "Sugar",
    "Sugar and Spice",
    "Sunset Blvd.",
    "Sunshine Cleaning",
    "Super 8",
    "Superbad",
    "Superfights",
    "Supergirl",
    "Surfer King, The",
    "Surrogates",
    "Suspect Zero",
    "Sweeney Todd: The Demon Barber of Fleet Street",
    "Sweet Hereafter, The",
    "Sweet Smell of Success",
    "Swingers",
    "Swordfish",
    "Synecdoche, New York",
    "Syriana",
    "TMNT",
    "TRON",
    "TRON: Legacy",
    "Take Shelter",
    "Taking Lives",
    "Taking Sides",
    "Taking of Pelham One Two Three, The",
    "Talented Mr. Ripley, The",
    "Tall in the Saddle",
    "Tamara Drewe",
    "Taxi Driver",
    "Teachers' Lounge, The",
    "Ted",
    "Teenage Mutant Ninja Turtles: Mutant Mayhem",
    "Tenet",
    "Terminator",
    "Terminator 2: Judgement Day",
    "Terminator Salvation",
    "The Rage: Carrie 2",
    "Thelma & Louise",
    "Theory of Everything, The",
    "There's Something About Mary",
    "They",
    "Thing, The",
    "Things My Father Never Taught Me, The",
    "Thirteen Days",
    "This Boy's Life",
    "This is 40",
    "Thor",
    "Thor Ragnarok",
    "Three Kings",
    "Three Kings (Spoils of War)",
    "Three Men and a Baby",
    "Three Musketeers, The",
    "Thunderbirds",
    "Thunderheart",
    "Ticker",
    "Timber Falls",
    "Time Machine, The",
    "Tin Cup",
    "Tin Men",
    "Tinker Tailor Soldier Spy",
    "Titanic",
    "To Sleep with Anger",
    "Tombstone",
    "Tomorrow Never Dies",
    "Top Gun",
    "Total Recall",
    "Tourist, The",
    "Town, The",
    "Toy Story",
    "Traffic",
    "Training Day",
    "Trainspotting",
    "Transformers: The Movie",
    "Trap Livin'",
    "Tremors",
    "Tristan and Isolde",
    "Tropic Thunder",
    "Troy",
    "True Grit",
    "True Lies",
    "True Romance",
    "Truman Show, The",
    "Tucker and Dale vs Evil",
    "Twilight",
    "Twilight: New Moon",
    "Twin Peaks",
    "Twins",
    "Twister",
    "Two For The Money",
    "U Turn",
    "Ugly Truth, The",
    "Un Singe en Hiver",
    "Unbreakable",
    "Under Fire",
    "Unforgiven",
    "Unknown",
    "Up",
    "Up in the Air",
    "Usual Suspects, The",
    "V for Vendetta",
    "Valentine's Day",
    "Valkyrie",
    "Vanilla Sky",
    "Verdict, The",
    "Vertigo",
    "Very Bad Things",
    "Village, The",
    "Virtuosity",
    "Visitor, The",
    "Wag the Dog",
    "Walk to Remember, A",
    "Walking Tall",
    "Wall Street",
    "Wall Street: Money Never Sleeps",
    "Wall-E",
    "Wanted",
    "War Horse",
    "War for the Planet of the Apes",
    "War of the Worlds",
    "Warm Springs",
    "Warrior",
    "Watchmen",
    "Water for Elephants",
    "Way Back, The",
    "We Own the Night",
    "What About Bob?",
    "What Lies Beneath",
    "When Harry Met Sally",
    "When a Stranger Calls",
    "While She Was Out",
    "Whiplash",
    "Whistleblower, The",
    "White Christmas",
    "White Jazz",
    "White Ribbon, The",
    "White Squall",
    "Whiteout",
    "Who Framed Roger Rabbit?",
    "Who's Your Daddy",
    "Wicked",
    "Wild At Heart",
    "Wild Bunch, The",
    "Wild Hogs",
    "Wild Things",
    "Wild Things: Diamonds in the Rough",
    "Wild Wild West",
    "Willow",
    "Win Win",
    "Wind Chill",
    "Withnail and I",
    "Witness",
    "Wizard of Oz, The",
    "Wolf of Wall Street, The",
    "Wonder Boys",
    "Wonder Woman",
    "Wonka",
    "Woodsman, The",
    "World is not Enough, The",
    "Wrestler, The",
    "X-Files: Fight the Future, The",
    "X-Men",
    "X-Men Origins: Wolverine",
    "Year One",
    "Yes Man",
    "You Can Count On Me",
    "You've Got Mail",
    "Youth in Revolt",
    "Zebra Girl",
    "Zero Dark Thirty",
    "Zerophilia",
    "Zone of Interest, The",
    "Zootopia",
    "eXistenZ",
    "xXx"]
    collector.collect_scripts(movies) 